server:
  port: 9090

spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10000ms
    database: 0
    lettuce:
      pool:
        min-idle: 0
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

system:
  qrcode:
    save-address: /data/file/qrcode/